// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: "postgresql://neondb_owner:npg_plyz6HAXNE7r@ep-nameless-smoke-ajeddw5q-pooler.c-3.us-east-2.aws.neon.tech/neondb?channel_binding=require&sslmode=require",
  },
});
